# Generated by Django 5.2.8 on 2025-11-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='Flagged as potential duplicate'),
        ),
    ]
