# Generated by Django 5.2.8 on 2025-11-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('OFFICER', 'Officer'), ('ADMIN', 'Admin')], default='CITIZEN', max_length=20),
        ),
    ]
