# Generated by Django 5.2.8 on 2025-11-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_petition_assigned_officer_auditlog_and_more'),
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department for officers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='petitions.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_officer',
            field=models.BooleanField(default=True, help_text='Whether officer is available for assignments'),
        ),
    ]
